package com.example.studynotes.service;

import com.example.studynotes.model.StudyNote;
import com.example.studynotes.model.ThemeSection;
import com.example.studynotes.model.enums.OutputFormat;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class StudyNotesService {

    private final OpenAiService openAiService;

    public StudyNotesService(OpenAiService openAiService) {
        this.openAiService = openAiService;
    }

    public StudyNote generate(String sourceFileName, String lectureText) {
        String markdown = openAiService.generateStudyNotesMarkdown(lectureText);
        String title = sourceFileName + " - Study Notes";

        // Keep model simple; structured fields can be added later if needed.
        return new StudyNote(title, "Generated by OpenAI from lecture PDF.",
                List.of(new ThemeSection("Generated Notes", markdown)),
                "Review the major themes and examples above.", OutputFormat.MARKDOWN);
    }
}
